### ISSUE TITLE
'autodynatrace.wrappers.django' - RecursionError: maximum recursion depth

### ISSUE THREAD

**Issue by jamesjsanders** [dlopes7/autodynatrace#24]
When running a Django shell command `python manage.py migrate --noinput` we get the error **_RecursionError: maximum recursion depth exceeded_**. 

Autodynatrace Version: **1.0.37**
Service: **Django/UWSGI**
Django Version: **2.2.8**
Sentry SDK Version: **0.9.5**
Server: **Linux 4.15.0-1063-aws #67-Ubuntu**
Python Version: **3.6.8**

### ERROR 
```
$ python manage.py migrate --noinput
  File "/srv/venvs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/srv/venvs/py3/lib/python3.6/site-packages/sentry_sdk/integrations/django/__init__.py", line 469, in execute
    return real_execute(self, sql, params)
  File "/srv/venvs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 74, in _execute_with_wrappers
    for wrapper in reversed(self.db.execute_wrappers):
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/venvs/py3/lib/python3.6/site-packages/django/db/backends/utils.py", line 23, in __getattr__
    cursor_attr = getattr(self.cursor, attr)
  [Previous line repeated 997 more times]
RecursionError: maximum recursion depth exceeded
```
### Python Code
```
    def execute(self, sql, params=None):
        return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

    def _execute_with_wrappers(self, sql, params, many, executor):
        context = {'connection': self.db, 'cursor': self}
        for wrapper in reversed(self.db.execute_wrappers):
            executor = functools.partial(wrapper, executor)
        return executor(sql, params, many, context)
```
### Screen Shot
![image](https://user-images.githubusercontent.com/11224488/79289794-28486180-7e7f-11ea-943b-314a450c2859.png)

**Comment by dlopes7** [comment]
Thanks for reporting, commit https://github.com/dlopes7/autodynatrace/commit/35f281c52f5b7630d9ba2ed3f1498d487cd183f0 introduced this bug, it is fixed in 1.0.38
